version: "3"

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "5000:3000"
        # Não funciona no Windows =(
        # Descomentar se você estiver no Linux ou OSX
        # volumes:
        #     - ./dist/:/usr/app/dist/
        networks:
            - backend

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - backend

networks:
    backend: